name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    runs_on: ubuntu_latest
    steps:
      - name: Downoload the code
      uses: actions/checkout@v4
      - name : Install Python
      uses: actions/setup-python@v5
      with:
         python-version "3.11"
      - name :install requirements
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      -name: Run test
      rin: pytest
